// categories.js
export const categories = [
  "Catering",
  "Photography",
  "Videography",
  "Decoration",
  "Music/DJ",
  "Makeup Artists",
  "Bridal Wear",
  "Groom Wear",
  "Event Planning",
  "Transportation",
  "Florists",
  "Lighting & Effects",
  "Wedding Cakes",
  "Invitations & Stationery",
  "Entertainment",
  "Security Services",
  "Officiants",
  "Wedding Venues",
  "Destination Wedding Planners",
  "Wedding Rentals",
  "Bar Services",
  "Wedding Photobooks/Albums",
  "Henna Artists",
  "Pre-Wedding Shoots",
  "Honeymoon Planners",
  "Gift Registry Services",
  "Hair Stylists",
  "Sound & Audio",
];
